---

- name: Chroot and Build Additional Tools - Chapter 7
  become: true
  become_user: root
  block:

    - name: Change ownership to root:root for {{ proxy_env.LFS }}
      ansible.builtin.file:
        path: "{{ proxy_env.LFS }}/{{ item }}"
        owner: root
        group: root
        recurse: true
      loop:
        - usr
        - var
        - etc
        - tools
        # remove symlinked dirs as they cause errors, and are unnecessary
        # - lib
        # - bin
        # - sbin

    - name: Change ownership on to root:root on x86_64 for {{ proxy_env.LFS~'/lib64' }}
      ansible.builtin.file:
        path: '{{ proxy_env.LFS }}/lib64'
        owner: root
        group: root
      when: gcc.lfstriplet is regex("^x86_64")

    - name: Create VFS directories $LFS/{dev,proc,sys,run}
      ansible.builtin.file:
        path: "{{ proxy_env.LFS }}/{{ item }}"
        state: directory
        owner: root
        group: root
      loop:
        - dev
        - proc
        - sys
        - run

#   - name: Mount and populate /dev
#     ansible.posix.mount:
#       path: "{{ item.path }}"
#       src: "{{ item.src }}"
#       fstype: "{{ item.fstype }}"
#       opts: "{{ item.opts }}"
#       state: ephemeral
#     loop:
#       - { path: '{{ proxy_env.LFS }}/dev', src: '/dev', fstype: 'none', opts: 'bind' }
#       - { path: '{{ proxy_env.LFS }}/dev/pts', src: 'devpts', fstype: 'devpts', opts: 'gid=5,mode=0620' }
#       - { path: '/proc', src: 'proc', fstype: 'proc', opts: 'defaults' }
#       - { path: '/sys', src: 'sysfs', fstype: 'sysfs', opts: 'defaults' }
#       - { path: '/run', src: 'tmpfs', fstype: 'tmpfs', opts: 'defaults' }

    - name: Mount and populate /dev
      block:

        - name: "Mount system filesystems"
          ansible.builtin.include_role:
            name: cam
          vars:
            cam_device: "{{ item.device }}"
            cam_mountpoint: "{{ item.mountpoint }}"
            cam_fstype: "{{ item.fstype }}"
            cam_extraopts: "{{ item.extraopts }}"
          loop:
            - device: /dev
              mountpoint: "{{ proxy_env.LFS }}/dev"
              fstype: ""
              extraopts: "--bind"
            - device: /dev/pts
              mountpoint: "{{ proxy_env.LFS }}/dev/pts"
              fstype: "devpts"
              extraopts: "-o gid=5,mode=0620"
            - device: sysfs
              mountpoint: "{{ proxy_env.LFS }}/sys"
              fstype: "sysfs"
              extraopts: ""
            - device: tmpfs
              mountpoint: "{{ proxy_env.LFS }}/run"
              fstype: "tmpfs"
              extraopts: ""

        - name: Mount /dev/shm
          ansible.builtin.shell: |
            if [ -h {{ proxy_env.LFS }}/dev/shm ]; then
              install -v -d -m 1777 {{ proxy_env.LFS }}$(realpath /dev/shm)
            else
              grep ' {{ proxy_env.LFS }}/dev/shm ' /proc/mounts || \
                mount -vt tmpfs -o nosuid,nodev tmpfs {{ proxy_env.LFS }}/dev/shm
            fi
          when: proxy_env.LFS~'/run' is not mount

...
