---

- name: Build packages for lfs - Chapter 6
  become: true
  become_user: lfs
  block:
    - name: Build m4-1.4.19.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.2
        cmi_archive: m4-1.4.19.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr   \
          --host={{ proxy_env.LFS_TGT }} \
          --build=$(build-aux/config.guess)
        cmi_make_install_cmd: make DESTDIR={{ proxy_env.LFS }} install

    - name: Build ncurses-6.4-20230520.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.3
        cmi_archive: ncurses-6.4-20230520.tar.xz
        cmi_unarchive_extra: |
          sed -i s/mawk// configure
          mkdir build
          pushd build
            ../configure
            make -C include
            make -C progs tic
          popd
        cmi_configure_command: |
          ./configure --prefix=/usr                 \
                      --host={{ proxy_env.LFS_TGT }}\
                      --build=$(./config.guess)     \
                      --mandir=/usr/share/man       \
                      --with-manpage-format=normal  \
                      --with-shared                 \
                      --without-normal              \
                      --with-cxx-shared             \
                      --without-debug               \
                      --without-ada                 \
                      --disable-stripping           \
                      --enable-widec
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} TIC_PATH=$(pwd)/build/progs/tic install
          ln -sv libncursesw.so {{ proxy_env.LFS }}/usr/lib/libncurses.so
          sed -e 's/^#if.*XOPEN.*$/#if 1/' \
              -i $LFS/usr/include/curses.h

    - name: Build bash-5.2.21.tar.gz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.4
        cmi_archive: bash-5.2.21.tar.gz
        cmi_configure_command: |
          ./configure --prefix=/usr                      \
                      --build=$(sh support/config.guess) \
                      --host={{ proxy_env.LFS_TGT }}     \
                      --without-bash-malloc
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build coreutils-9.4.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.5
        cmi_archive: coreutils-9.4.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                      \
                      --host={{ proxy_env.LFS_TGT }}     \
                      --build=$(build-aux/config.guess)  \
                      --enable-install-program=hostname  \
                      --enable-no-install-program=kill,uptime
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install
        cmi_postinstall: |
          mv -v {{ proxy_env.LFS }}/usr/bin/chroot              {{ proxy_env.LFS }}/usr/sbin
          mkdir -pv {{ proxy_env.LFS }}/usr/share/man/man8
          mv -v {{ proxy_env.LFS }}/usr/share/man/man1/chroot.1 {{ proxy_env.LFS }}/usr/share/man/man8/chroot.8
          sed -i 's/"1"/"8"/'                                   {{ proxy_env.LFS }}/usr/share/man/man8/chroot.8

    - name: Build diffutils-3.10.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.6
        cmi_archive: diffutils-3.10.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                      \
                      --host={{ proxy_env.LFS_TGT }}     \
                      --build=$(sh support/config.guess) \
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build file-5.45.tar.gz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.7
        cmi_archive: file-5.45.tar.gz
        cmi_unarchive_extra: |
          mkdir build
          pushd build
            ../configure --disable-bzlib      \
                          --disable-libseccomp \
                          --disable-xzlib      \
                          --disable-zlib
            make
          popd
        cmi_configure_command: |
          ./configure --prefix=/usr                      \
                      --host={{ proxy_env.LFS_TGT }}     \
                      --build=$(sh support/config.guess) \
        cmi_make_cmd: |
          make FILE_COMPILE=$(pwd)/build/src/file -j {{ gcc.jobs }}
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install
        cmi_postinstall: |
          rm -v {{ proxy_env.LFS }}/usr/lib/libmagic.la

    - name: Build findutils-4.9.0.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.8
        cmi_archive: findutils-4.9.0.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --localstatedir=/var/lib/locate \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build gawk-5.3.0.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.9
        cmi_archive: gawk-5.3.0.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build grep-3.11.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.10
        cmi_archive: grep-3.11.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build gzip-1.13.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.11
        cmi_archive: gzip-1.13.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install
        cmi_debug: true

    - name: Build make-4.4.1.tar.gz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.12
        cmi_archive: make-4.4.1.tar.gz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --without-guile                 \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build patch-2.7.6.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.13
        cmi_archive: patch-2.7.6.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build sed-4.9.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.14
        cmi_archive: sed-4.9.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build tar-1.35.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.15
        cmi_archive: tar-1.35.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                   \
                      --host={{ proxy_env.LFS_TGT }}  \
                      --build=$(build-aux/config.guess)
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install

    - name: Build xz-5.4.7.tar.xz
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.16
        cmi_archive: xz-5.4.7.tar.xz
        cmi_configure_command: |
          ./configure --prefix=/usr                     \
                      --host={{ proxy_env.LFS_TGT }}    \
                      --build=$(build-aux/config.guess) \
                      --disable-static                  \
                      --docdir=/usr/share/doc/xz-5.4.7
        cmi_make_install_cmd: |
          make DESTDIR={{ proxy_env.LFS }} install
        cmi_postinstall:
          rm -v {{ proxy_env.LFS }}/usr/lib/liblzma.la

    - name: Build binutils-2.42.tar.xz - Pass 2
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.17
        cmi_archive: binutils-2.42.tar.xz
        cmi_unarchive_extra: |
          sed '6009s/$add_dir//' -i ltmain.sh
        cmi_configure_command: |
          ../configure --prefix=/usr                    \
                      --build=$(../config.guess)        \
                      --host={{ proxy_env.LFS_TGT }}    \
                      --disable-nls                     \
                      --enable-shared                   \
                      --enable-gprofng=no               \
                      --disable-werror                  \
                      --enable-64-bit-bfd               \
                      --enable-default-hash-style=gnu
        cmi_build_in_build: true
        cmi_postinstall: |
          rm -v {{ proxy_env.LFS }}/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}

    - name: Build gcc-13.2.0.tar.xz - Pass 2
      ansible.builtin.import_role:
        name: cmi
      vars:
        cmi_step: 6.18
        cmi_archive: gcc-13.2.0.tar.xz
        cmi_unarchive_extra: |
          pwd
          ls ..
          if [ ! -d mpfr ]; then
            tar -xf ../mpfr-4.2.1.tar.xz
            mv -v mpfr-4.2.1 mpfr
          fi
          if [ ! -d gmp ]; then
            tar -xf ../gmp-6.3.0.tar.xz
            mv -v gmp-6.3.0 gmp
          fi
          if [ ! -d mpc ]; then
            tar -xf ../mpc-1.3.1.tar.gz
            mv -v mpc-1.3.1 mpc
          fi
          case $( echo {{ gcc.lfstriplet }} | sed 's/-.*//' ) in
            x86_64)
              sed -e '/m64=/s/lib64/lib/' \
                  -i.orig gcc/config/i386/t-linux64
            ;;
          esac
          sed '/thread_header =/s/@.*@/gthr-posix.h/' \
              -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in
        cmi_configure_command: |
          ../configure                                                  \
              --build=$(../config.guess)                                \
              --host={{ proxy_env.LFS_TGT }}                            \
              --target={{ proxy_env.LFS_TGT }}                          \
              LDFLAGS_FOR_TARGET=-L$PWD/{{ proxy_env.LFS_TGT }}/libgcc  \
              --prefix=/usr                                             \
              --with-build-sysroot={{ proxy_env.LFS }}                  \
              --enable-default-pie                                      \
              --enable-default-ssp                                      \
              --disable-nls                                             \
              --disable-multilib                                        \
              --disable-libatomic                                       \
              --disable-libgomp                                         \
              --disable-libquadmath                                     \
              --disable-libsanitizer                                    \
              --disable-libssp                                          \
              --disable-libvtv                                          \
              --enable-languages=c,c++
        cmi_postinstall: |
          ln -sv gcc $LFS/usr/bin/cc
        cmi_build_in_build: true
        cmi_debug: true

...
