---

- name: Configure user in gitlab
  hosts: all

  tasks:

    - name: Create GitLab group
      community.general.gitlab_group:
        api_url: "https://{{ inventory_hostname }}"
        validate_certs: false
        name: users
        state: present

    - name: Create GitLab user
      community.general.gitlab_user:
        api_url: "https://{{ inventory_hostname }}"
        validate_certs: false
        name: Test User
        username: user1
        password: "{{ user1_password }}"
        email: me@example.com
        state: present
        group: users
        access_level: owner

...
