---

- name: Install GitLab CE
  hosts: all
  vars:
    deps:
      - curl
      - python3-policycoreutils
      - openssh-server
      - perl
      - python3-firewall
    services:
      - http
      - https
    gl_pkgs:
      - python3-gitlab
      - python3-requests
    ce_script_url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh"

  tasks:
    - name: Install EPEL release GPG key from https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      loop:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: Add epel repo for RHEL 9
      ansible.builtin.package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: Install package dependencies for gitlab-ce
      ansible.builtin.package:
        name: "{{ deps }}"
        state: present

    - name: Start and enable openssh-server
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true

    #- name: Enable needed services in firewalld permanently and immediately
    #  ansible.posix.firewalld:
    #    service: "{{ item }}"
    #    permanent: true
    #    immediate: true
    #    state: enabled
    #  loop: "{{ services }}"

    - name: Disable and stop sendmail
      ansible.builtin.service:
        name: sendmail
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove sendmail package
      ansible.builtin.package:
        name: sendmail
        state: absent

    - name: Install postfix package
      ansible.builtin.package:
        name: postfix
        state: present

    - name: Start and enable postfix service
      ansible.builtin.service:
        name: postfix
        state: started
        enabled: true

    - name: Download repository installation script
      ansible.builtin.get_url:
        url: "{{ ce_script_url }}"
        dest: /tmp/gitlab-ce.sh
        mode: '0755'

    - name: Create the directory '/etc/gitlab'
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/gitlab
        - /etc/gitlab/ssl

    - name: Create private key (RSA, 4096 bits) for gitlab
      community.crypto.openssl_privatekey:
        path: /etc/gitlab/ssl/gitlab.key

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/gitlab/ssl/gitlab.crt
        privatekey_path: /etc/gitlab/ssl/gitlab.key
        provider: selfsigned

    - name: Create the file '/etc/gitlab/gitlab.rb' from the template 'gitlab.rb.j2'
      ansible.builtin.template:
        src: gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        mode: '0644'
      register: gitlab_config

    - name: Execute downloaded installation script
      ansible.builtin.command: /tmp/gitlab-ce.sh
      args:
        creates: /etc/yum.repos.d/gitlab_gitlab-ee.repo
      environment:
        os: el
        dist: 9

    - name: Install the gitlab-ee package
      ansible.builtin.package:
        name: gitlab-ee
        state: present
      environment:
        EXTERNAL_URL: "https://{{ inventory_hostname }}"

    - name: Install gl_pkgs packages
      ansible.builtin.package:
        name: "{{ gl_pkgs }}"
        state: present
    
    - name: Run gitlab-ctl reconfigure when /etc/gitlab/gitlab.rb is updated
      ansible.builtin.command: gitlab-ctl reconfigure
      args:
        creates: /var/opt/gitlab/bootstrapped
      when: gitlab_config.changed

...

