---

- name: Install GitLab CE
  hosts: all
  vars:
    deps:
      - curl
      - python3-policycoreutils
      - openssh-server
      - perl
    services:
      - http
      - https
    gl_pkgs:
      - python3-gitlab
      - python3-requests
    ce_script_url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh"

  tasks:
    - name: Install package dependencies for gitlab-ce
      ansible.builtin.package:
        name: "{{ deps }}"
        state: present

    - name: Start and enable openssh-server
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: true

    - name: Enable needed services in firewalld permanently and immediately
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ services }}"

    - name: Disable and stop sendmail
      ansible.builtin.service:
        name: sendmail
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove sendmail package
      ansible.builtin.package:
        name: sendmail
        state: absent

    - name: Install postfix package
      ansible.builtin.package:
        name: postfix
        state: present

    - name: Start and enable postfix service
      ansible.builtin.service:
        name: postfix
        state: started
        enabled: true

    - name: Download repository installation script
      ansible.builtin.get_url:
        url: "{{ ce_script_url }}"
        dest: /tmp/gitlab-ce.sh
        mode: '0755'

    - name: Execute downloaded installation script
      ansible.builtin.command: /tmp/gitlab-ce.sh
      args:
        creates: /etc/yum.repos.d/gitlab_gitlab-ee.repo
      environment:
        os: el
        dist: 9

    - name: Install the gitlab-ee package
      ansible.builtin.package:
        name: gitlab-ee
        state: present
      environment:
        EXTERNAL_URL: "https://{{ inventory_hostname }}"

    - name: Install gl_pkgs packages
      ansible.builtin.package:
        name: "{{ gl_pkgs }}"
        state: present

...

