---

- name: Configure user in gitlab
  hosts: all

  tasks:

    - name: Install python3.11-pip package
      become: true
      ansible.builtin.package:
        name: python3.11-pip
        state: present

    - name: Install gitlab python module
      ansible.builtin.pip:
        name: python-gitlab
        state: present

    - name: Create GitLab group
      community.general.gitlab_group:
        api_url: "https://{{ inventory_hostname }}"
        api_token: "{{ gl_token }}"
        validate_certs: false
        name: group1
        state: present

    - name: Create GitLab user
      community.general.gitlab_user:
        api_url: "https://{{ inventory_hostname }}"
        api_token: "{{ gl_token }}"
        validate_certs: false
        name: Test User
        username: user1
        password: "{{ user1_password }}"
        email: me@example.com
        state: present
        group: group1
        access_level: owner

...
