---

- hosts: all

  tasks:

    - name: test
      debug:
        msg: "this is a test"

    - name: command test
      command: whoami

    - name: shell test
      shell: whoami

    - name: Ping Output
      shell: ping -c 2 {{ip}}
      ignore_errors: true
      register: op

    - name: ping output
      debug:
        var: op


...
