---
plugin: amazon.aws.aws_ec2
profile: "{{ lookup('env', 'AWS_PROFILE') | default('aws_profile', true) }}"
regions:
  - us-east-1
keyed_groups:
  - key: tags
    prefix: tag
compose:
  ansible_host: public_dns_name